version: 2.1
jobs:
  test:
    docker:
      - image: irespaldiza/git:latest
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
          - de:0d:9e:c1:3b:25:b6:9b:b6:4c:ee:25:53:f6:e3:04
      - run:
          name: "test"
          command: |
            date > a
            git version

workflows:
  version: 2
  build-release:
    jobs:
      - test:
          filters:
            branches:
              ignore: main
