version: 2.1
jobs:
  test:
    docker:
      - image: irespaldiza/git:latest
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
          - de:0d:9e:c1:3b:25:b6:9b:b6:4c:ee:25:53:f6:e3:04
      - run:
          command: |
            date > $(date | awk '{print $4}')
            git config user.name "okteto"
            git config user.email "ci@okteto.com
            git add --all
            git commit -m "cc"
            git push

workflows:
  version: 2
  build-release:
    jobs:
      - test:
          filters:
            branches:
              ignore: main
